from pyrogram import Client, filters
from utils.helper import generate_poster_image
import logging
import asyncio

# Command Mappings associated with Media Types
# (Command, TemplateName, MediaType)
COMMAND_MAP = {
    "ani": ("ani", "ANIME"),
    "anim": ("anim", "MANGA"),
    "crun": ("crun", "ANIME"),
    "light": ("light", "ANIME"),
    "lightm": ("lightm", "MANGA"),
    "net": ("net", "ANIME"),
    "netm": ("netm", "MANGA"),
    "dark": ("dark", "ANIME"),
    "darkm": ("darkm", "MANGA"),
    "netcr": ("netcr", "ANIME"),
    "mod": ("mod", "ANIME"),
    "modm": ("modm", "MANGA")
}

from utils.upload import upload_to_imgbb



from utils.db import db
from config import Config

async def generic_gen(client, message, template, media_type):
    if len(message.command) < 2:
        await message.reply_text(f"⚠️ **Usage:** `/{message.command[0]} <name>`\nExample: `/{message.command[0]} Naruto`")
        return

    # 1. Check Premium Status & Limits
    user_id = message.from_user.id
    is_premium = await db.is_premium_user(user_id)
    
    if is_premium:
        rank = await db.get_premium_user_rank(user_id)
        limit = Config.TASK_LIMITS.get(rank, Config.TASK_LIMITS["gold"]) # Default to gold if rank unknown? Or safe fallback
    else:
        rank = "default"
        limit = Config.TASK_LIMITS["default"]
        
    # Check Limit

    allowed = await db.check_and_update_usage(user_id, limit)
    if not allowed:
        buttons = [[
            InlineKeyboardButton("💎 Upgrade to Premium", callback_data="plans_menu")
            # We don't have plans_menu callback yet, let's use check /plans
        ]]
        # Actually /plans is a command
        await message.reply_text(
            f"🚫 **Daily Limit Reached!**\n\n"
            f"You have used all **{limit}** free generations for today.\n"
            f"Upgrade to Premium for more!",
            quote=True
        )
        return

    query = message.text.split(None, 1)[1]
    status = await message.reply_text(f"🎨 **Designing {template} poster for:** `{query}`...")
    
    try:
        # Pass is_premium to skip watermark if applicable
        poster_io = await generate_poster_image(template, query, media_type, is_premium=is_premium)
        
        if not poster_io:
            await status.edit_text(f"❌ **Not Found.**\nCould not find content for `{query}`.")
            return

        await status.edit_text("📤 **Uploading...**")
        poster_io.name = f"{template}_{query}.jpg"
        
        # Upload to ImgBB
        img_url = upload_to_imgbb(poster_io)
        
        caption = f"Generated by **Poster Bot** 🎨"
        if img_url:
            caption += f"\n\n🔗 **Link:** {img_url}"
        
        # Add Channel Button
        from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton
        buttons = InlineKeyboardMarkup([
            [InlineKeyboardButton("📢 Join Update Channel", url="https://t.me/Blaze_Updatez")]
        ])

        await message.reply_photo(
            photo=poster_io,
            caption=caption,
            reply_markup=buttons
        )
        await status.delete()
        
    except Exception as e:
        logging.error(f"Error in command /{message.command[0]}: {e}", exc_info=True)
        await status.edit_text("⚠️ **Error.**\nAn unexpected error occurred. Please try again later.")

# Register Command Handlers
@Client.on_message(filters.command(list(COMMAND_MAP.keys())))
async def router(client, message):
    cmd = message.command[0]
    if cmd in COMMAND_MAP:
        template, media_type = COMMAND_MAP[cmd]
        await generic_gen(client, message, template, media_type)
